project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - research.qmd
    - blog.qmd
    - newsletter.qmd
    - cv.qmd
    - contacto.qmd
    - posts/**/*.ipynb
    - posts/**/*.qmd

website:
  title: "edalytics"
  description: "Economía aplicada, econometría y análisis de datos con Python"
  favicon: favicon.png

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - href: newsletter.qmd
        text: Newsletter
      - href: cv.qmd
        text: CV
      - href: about.qmd
        text: About
      - href: contacto.qmd
        text: Contacto
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/eduard-de-jesus-romero-mercedes-580753125/
      - icon: twitter-x
        href: https://x.com/MercedesEd67541
      - icon: github
        href: https://github.com/ji-square
      - icon: youtube
        href: https://www.youtube.com/channel/UC7_KVXwhrDiTaagGHCEir-Go

  page-footer:
    left: "© 2026 Eduard Romero — edalytics"
    center: |
      <a href="https://ko-fi.com/tu-usuario" target="_blank">
        <img src="https://cdn.ko-fi.com/cdn/kofi2.png?v=3" 
             alt="Buy Me a Coffee at ko-fi.com" 
             style="height: 30px;">
      </a>
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/eduard-de-jesus-romero-mercedes-580753125/
      - icon: twitter-x
        href: https://x.com/edalytics_
      - icon: github
        href: https://github.com/ji-square
      - icon: youtube
        href: https://www.youtube.com/channel/UC7_KVXwhrDiTaagGHCEir-Go

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    smooth-scroll: true